---

- hosts: all
  connection: local
  user: "{{ user }}"

  vars_files:
    - vars.yml

  roles:
    - { role: apps, tags: ['apps'] }
    - { role: dotfiles, tags: ['dotfiles'] }
    - { role: osx, tags: ['osx'] }
    - { role: dock, tags: ['dock'] }
    - { role: terminal, tags: ['terminal'] }
    - { role: mackup, tags: ['mackup'] }
    - { role: account, tags: ['account'] }
    - { role: vagrant, tags: ['vagrant'] }