---

- name: Link Mackup config dir
  file: src=/Users/{{ user }}/Dropbox/Mackup/.mackup dest=/Users/{{ user }}/.mackup state=link

- name: Copy custom config files
  copy: src={{ item }} dest=/Users/{{ user }}/.mackup
  with_items:
    - dotfiles.cfg

- name: Install mackup
  homebrew: name=mackup state=present

- name: Open dropbox and make sure it's active and configured
  command: open /Applications/Dropbox.app
