- name: Copy dotfiles
  template: src="{{ item }}.j2" dest="{{ dotfiles_dir }}/.{{ item }}"
  ignore_errors: yes
  with_items:
    - gitconfig
    - bash_prompt
    - hushlogin
    - exports
    - gitattributes
    - curlrc
    - aliases
    - bash_profile
    - vimrc
    - inputrc
    - symfony2-autocomplete.bash
    - git-flow-autocomplete.bash
    - git-completion.bash
    - boot2docker.bash
    - docker-alias.bash
    - docker-autocomplete.bash


- name: Create vim dirs
  file: path="{{ item }}" state=directory
  with_items:
    - ~/.vim/swaps
    - ~/.vim/backups
    - ~/.vim/undo
